const africanCountriesAndCapitals = {
    "Alžírsko": "Alžír",
    "Angola": "Luanda",
    "Benin": "Porto-Novo",
    "Botswana": "Gaborone",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Gitega",
    "Kapverdy": "Praia",
    "Kamerun": "Yaoundé",
    "Středoafrická republika": "Bangui",
    "Čad": "Ndžaména",
    "Komory": "Moroni",
    "Demokratická republika Kongo": "Kinshasa",
    "Republika Kongo": "Brazzaville",
    "Džibutsko": "Džibuti",
    "Egypt": "Káhira",
    "Rovníková Guinea": "Malabo",
    "Eritrea": "Asmara",
    "Eswatini": "Mbabane",
    "Etiopie": "Addis Abeba",
    "Gabon": "Libreville",
    "Gambie": "Banjul",
    "Ghana": "Accra",
    "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau",
    "Pobřeží slonoviny": "Yamoussoukro",
    "Keňa": "Nairobi",
    "Lesotho": "Maseru",
    "Libérie": "Monrovia",
    "Libye": "Tripolis",
    "Madagaskar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Mali": "Bamako",
    "Mauritánie": "Nouakchott",
    "Mauricius": "Port Louis",
    "Maroko": "Rabat",
    "Mosambik": "Maputo",
    "Namibie": "Windhoek",
    "Niger": "Niamey",
    "Nigérie": "Abúja",
    "Rwanda": "Kigali",
    "Svatý Tomáš a Princův ostrov": "São Tomé",
    "Senegal": "Dakar",
    "Seychely": "Victoria",
    "Sierra Leone": "Freetown",
    "Somálsko": "Mogadišu",
    "Jižní Afrika": "Pretoria",
    "Jižní Súdán": "Juba",
    "Súdán": "Chartúm",
    "Tanzanie": "Dodoma",
    "Togo": "Lomé",
    "Tunisko": "Tunis",
    "Uganda": "Kampala",
    "Zambie": "Lusaka",
    "Zimbabwe": "Harare"
};

export default africanCountriesAndCapitals;
