const americanCountriesAndCapitals = {
    "Argentina": "Buenos Aires",
    "Bolívie": "Sucre",
    "Brazílie": "Brasília",
    "Chile": "Santiago",
    "Kolumbie": "Bogotá",
    "Ekvádor": "Quito",
    "Guyana": "Georgetown",
    "Paraguay": "Asunción",
    "Peru": "Lima",
    "Surinam": "Paramaribo",
    "Uruguay": "Montevideo",
    "Venezuela": "Caracas",
    "Antigua a Barbuda": "Saint John's",
    "Bahamy": "Nassau",
    "Barbados": "Bridgetown",
    "Belize": "Belmopan",
    "Kanada": "Ottawa",
    "Kostarika": "San José",
    "Kuba": "Havana",
    "Dominika": "Roseau",
    "Dominikánská republika": "Santo Domingo",
    "Salvador": "San Salvador",
    "Grenada": "St. George's",
    "Guatemala": "Guatemala City",
    "Haiti": "Port-au-Prince",
    "Honduras": "Tegucigalpa",
    "Jamajka": "Kingston",
    "Mexiko": "Mexico City",
    "Nikaragua": "Managua",
    "Panama": "Panama City",
    "Svatý Kryštof a Nevis": "Basseterre",
    "Svatá Lucie": "Castries",
    "Svatý Vincenc a Grenadiny": "Kingstown",
    "Trinidad a Tobago": "Port of Spain",
    "Spojené státy americké": "Washington, D.C."
};

export default americanCountriesAndCapitals;
