const asianCountriesAndCapitals = {
    "Afghánistán": "Kábul",
    "Arménie": "Jerevan",
    "Ázerbájdžán": "Baku",
    "Bahrajn": "Manáma",
    "Bangladéš": "Dháka",
    "Bhútán": "Thimphu",
    "Brunej": "Bandar Seri Begawan",
    "Kambodža": "Phnompenh",
    "Čína": "Peking",
    "Kypr": "Nikósie",
    "Gruzie": "Tbilisi",
    "Indie": "Nové Dillí",
    "Indonésie": "Jakarta",
    "Írán": "Teherán",
    "Irák": "Bagdád",
    "Izrael": "Jeruzalém",
    "Japonsko": "Tokio",
    "Jordánsko": "Ammán",
    "Kazachstán": "Nur-Sultan",
    "Kuvajt": "Kuvajt",
    "Kyrgyzstán": "Biškek",
    "Laos": "Vientiane",
    "Libanon": "Bejrút",
    "Malajsie": "Kuala Lumpur",
    "Maledivy": "Malé",
    "Mongolsko": "Ulánbátar",
    "Myanmar": "Neipyijto",
    "Nepál": "Káthmándú",
    "Severní Korea": "Pchjongjang",
    "Omán": "Maskat",
    "Pákistán": "Islámábád",
    "Filipíny": "Manila",
    "Katar": "Dauhá",
    "Saúdská Arábie": "Rijád",
    "Singapur": "Singapur",
    "Jižní Korea": "Soul",
    "Srí Lanka": "Kolombo",
    "Sýrie": "Damašek",
    "Tchaj-wan": "Tchaj-pej",
    "Tádžikistán": "Dušanbe",
    "Thajsko": "Bangkok",
    "Východní Timor": "Dili",
    "Turecko": "Ankara",
    "Turkmenistán": "Ašchabad",
    "Spojené arabské emiráty": "Abú Zabí",
    "Uzbekistán": "Taškent",
    "Vietnam": "Hanoj",
    "Jemen": "San'á"
};

export default asianCountriesAndCapitals;
