const countriesAndCapitals = {
    "Afghánistán": "Kábul",
    "Albánie": "Tirana",
    "Alžírsko": "Alžír",
    "Andorra": "Andorra la Vella",
    "Angola": "Luanda",
    "Antigua a Barbuda": "Saint John's",
    "Argentina": "Buenos Aires",
    "Arménie": "Jerevan",
    "Austrálie": "Canberra",
    "Rakousko": "Vídeň",
    "Ázerbájdžán": "Baku",
    "Bahamy": "Nassau",
    "Bahrajn": "Manáma",
    "Bangladéš": "Dháka",
    "Barbados": "Bridgetown",
    "Bělorusko": "Minsk",
    "Belgie": "Brusel",
    "Belize": "Belmopan",
    "Benin": "Porto-Novo",
    "Bhútán": "Thimphu",
    "Bolívie": "Sucre",
    "Bosna a Hercegovina": "Sarajevo",
    "Botswana": "Gaborone",
    "Brazílie": "Brasília",
    "Brunej": "Bandar Seri Begawan",
    "Bulharsko": "Sofie",
    "Burkina Faso": "Ouagadougou",
    "Burundi": "Gitega",
    "Kapverdy": "Praia",
    "Kambodža": "Phnompenh",
    "Kamerun": "Yaoundé",
    "Kanada": "Ottawa",
    "Středoafrická republika": "Bangui",
    "Čad": "N'Djamena",
    "Chile": "Santiago",
    "Čína": "Peking",
    "Kolumbie": "Bogotá",
    "Komory": "Moroni",
    "Kongo (Brazzaville)": "Brazzaville",
    "Kostarika": "San José",
    "Chorvatsko": "Záhřeb",
    "Kuba": "Havana",
    "Kypr": "Nikósie",
    "Česko": "Praha",
    "Dánsko": "Kodaň",
    "Džibutsko": "Džibuti",
    "Dominika": "Roseau",
    "Dominikánská republika": "Santo Domingo",
    "Ekvádor": "Quito",
    "Egypt": "Káhira",
    "Salvador": "San Salvador",
    "Rovníková Guinea": "Malabo",
    "Eritrea": "Asmara",
    "Estonsko": "Tallinn",
    "Eswatini": "Mbabane",
    "Etiopie": "Addis Abeba",
    "Fidži": "Suva",
    "Finsko": "Helsinky",
    "Francie": "Paříž",
    "Gabon": "Libreville",
    "Gambie": "Banjul",
    "Gruzie": "Tbilisi",
    "Německo": "Berlín",
    "Ghana": "Accra",
    "Řecko": "Atény",
    "Grenada": "St. George's",
    "Guatemala": "Guatemala",
    "Guinea": "Conakry",
    "Guinea-Bissau": "Bissau",
    "Guyana": "Georgetown",
    "Haiti": "Port-au-Prince",
    "Honduras": "Tegucigalpa",
    "Maďarsko": "Budapešť",
    "Island": "Reykjavík",
    "Indie": "Nové Dillí",
    "Indonésie": "Jakarta",
    "Írán": "Teherán",
    "Irák": "Bagdád",
    "Irsko": "Dublin",
    "Izrael": "Jeruzalém",
    "Itálie": "Řím",
    "Jamajka": "Kingston",
    "Japonsko": "Tokio",
    "Jordánsko": "Ammán",
    "Kazachstán": "Nur-Sultan",
    "Keňa": "Nairobi",
    "Kiribati": "South Tarawa",
    "Severní Korea": "Pchjongjang",
    "Jižní Korea": "Soul",
    "Kosovo": "Priština",
    "Kuvajt": "Kuvajt",
    "Kyrgyzstán": "Biškek",
    "Laos": "Vientiane",
    "Lotyšsko": "Riga",
    "Libanon": "Bejrút",
    "Lesotho": "Maseru",
    "Libérie": "Monrovia",
    "Libye": "Tripolis",
    "Lichtenštejnsko": "Vaduz",
    "Litva": "Vilnius",
    "Lucembursko": "Lucemburk",
    "Madagaskar": "Antananarivo",
    "Malawi": "Lilongwe",
    "Malajsie": "Kuala Lumpur",
    "Maledivy": "Malé",
    "Mali": "Bamako",
    "Malta": "Valletta",
    "Marshallovy ostrovy": "Majuro",
    "Mauritánie": "Nouakchott",
    "Mauricius": "Port Louis",
    "Mexiko": "Mexiko City",
    "Mikronésie": "Palikir",
    "Moldavsko": "Kišiněv",
    "Monako": "Monako",
    "Mongolsko": "Ulánbátar",
    "Černá Hora": "Podgorica",
    "Maroko": "Rabat",
    "Mosambik": "Maputo",
    "Myanmar": "Naypyidaw",
    "Namibie": "Windhoek",
    "Nauru": "Yaren",
    "Nepál": "Káthmándú",
    "Nizozemsko": "Amsterdam",
    "Nový Zéland": "Wellington",
    "Nikaragua": "Managua",
    "Niger": "Niamey",
    "Nigérie": "Abuja",
    "Severní Makedonie": "Skopje",
    "Norsko": "Oslo",
    "Omán": "Maskat",
    "Pákistán": "Islámábád",
    "Palau": "Ngerulmud",
    "Palestina": "Jeruzalém",
    "Panama": "Panama City",
    "Papua-Nová Guinea": "Port Moresby",
    "Paraguay": "Asunción",
    "Peru": "Lima",
    "Filipíny": "Manila",
    "Polsko": "Varšava",
    "Portugalsko": "Lisabon",
    "Katar": "Dauhá",
    "Rumunsko": "Bukurešť",
    "Rusko": "Moskva",
    "Rwanda": "Kigali",
    "Svatý Kryštof a Nevis": "Basseterre",
    "Svatá Lucie": "Castries",
    "Svatý Vincenc a Grenadiny": "Kingstown",
    "Samoa": "Apia",
    "San Marino": "San Marino",
    "Svatý Tomáš a Princův ostrov": "São Tomé",
    "Saúdská Arábie": "Rijád",
    "Senegal": "Dakar",
    "Srbsko": "Bělehrad",
    "Seychely": "Victoria",
    "Sierra Leone": "Freetown",
    "Singapur": "Singapur",
    "Slovensko": "Bratislava",
    "Slovinsko": "Lublaň",
    "Šalamounovy ostrovy": "Honiara",
    "Somálsko": "Mogadišo",
    "Jižní Afrika": "Pretoria",
    "Jižní Súdán": "Džuba",
    "Španělsko": "Madrid",
    "Srí Lanka": "Šrí Džajavardanapura Kotte",
    "Súdán": "Chartúm",
    "Surinam": "Paramaribo",
    "Švédsko": "Stockholm",
    "Švýcarsko": "Bern",
    "Sýrie": "Damašek",
    "Tchaj-wan": "Tchaj-pej",
    "Tádžikistán": "Dušanbe",
    "Tanzanie": "Dodoma",
    "Thajsko": "Bangkok",
    "Timor-Leste": "Dili",
    "Togo": "Lomé",
    "Tonga": "Nuku'alofa",
    "Trinidad a Tobago": "Port of Spain",
    "Tunisko": "Tunis",
    "Turecko": "Ankara",
    "Turkmenistán": "Ašchabad",
    "Tuvalu": "Funafuti",
    "Uganda": "Kampala",
    "Ukrajina": "Kyjev",
    "Spojené arabské emiráty": "Abú Zabí",
    "Spojené království": "Londýn",
    "Spojené státy": "Washington, D.C.",
    "Uruguay": "Montevideo",
    "Uzbekistán": "Taškent",
    "Vanuatu": "Port Vila",
    "Vatikán": "Vatikán",
    "Venezuela": "Caracas",
    "Vietnam": "Hanoj",
    "Jemen": "San'á",
    "Zambie": "Lusaka",
    "Zimbabwe": "Harare"
    
        


    // Přidejte další země a hlavní města zde
};
export default countriesAndCapitals;
