const easiestCountriesAndCapitals = {
    "Austrálie": "Canberra",
    "Rakousko": "Vídeň",
    "Belgie": "Brusel",
    "Brazílie": "Brasília",
    "Kanada": "Ottawa",
    "Čína": "Peking",
    "Dánsko": "Kodaň",
    "Egypt": "Káhira",
    "Finsko": "Helsinky",
    "Francie": "Paříž",
    "Německo": "Berlín",
    "Řecko": "Athény",
    "Indie": "Nové Dillí",
    "Indonésie": "Jakarta",
    "Írán": "Teherán",
    "Irák": "Bagdád",
    "Irsko": "Dublin",
    "Itálie": "Řím",
    "Japonsko": "Tokio",
    "Mexiko": "Mexico City",
    "Nizozemsko": "Amsterdam",
    "Nový Zéland": "Wellington",
    "Norsko": "Oslo",
    "Pákistán": "Islamábád",
    "Peru": "Lima",
    "Filipíny": "Manila",
    "Polsko": "Varšava",
    "Portugalsko": "Lisabon",
    "Rusko": "Moskva",
    "Saúdská Arábie": "Rijád",
    "Jižní Afrika": "Kapské Město",
    "Jižní Korea": "Soul",
    "Španělsko": "Madrid",
    "Švédsko": "Stockholm",
    "Švýcarsko": "Curych",
    "Thajsko": "Bangkok",
    "Turecko": "Ankara",
    "Ukrajina": "Kyjev",
    "Spojené arabské emiráty": "Abú Zabí",
    "Spojené království": "Londýn",
    "Spojené státy americké": "Washington, D.C.",
    "Vietnam": "Hanoj"
};

export default easiestCountriesAndCapitals;
