const europeanCountriesAndCapitals = {
    "Albánie": "Tirana",
    "Andorra": "Andorra la Vella",
    "Rakousko": "Vídeň",
    "Bělorusko": "Minsk",
    "Belgie": "Brusel",
    "Bosna a Hercegovina": "Sarajevo",
    "Bulharsko": "Sofie",
    "Chorvatsko": "Záhřeb",
    "Kypr": "Nikósie",
    "Česká republika": "Praha",
    "Dánsko": "Kodaň",
    "Estonsko": "Tallinn",
    "Finsko": "Helsinky",
    "Francie": "Paříž",
    "Německo": "Berlín",
    "Řecko": "Atény",
    "Maďarsko": "Budapešť",
    "Island": "Reykjavík",
    "Irsko": "Dublin",
    "Itálie": "Řím",
    "Kosovo": "Priština",
    "Lotyšsko": "Riga",
    "Lichtenštejnsko": "Vaduz",
    "Litva": "Vilnius",
    "Lucembursko": "Lucemburk",
    "Malta": "Valletta",
    "Moldavsko": "Kišiněv",
    "Monako": "Monako",
    "Černá Hora": "Podgorica",
    "Nizozemsko": "Amsterdam",
    "Severní Makedonie": "Skopje",
    "Norsko": "Oslo",
    "Polsko": "Varšava",
    "Portugalsko": "Lisabon",
    "Rumunsko": "Bukurešť",
    "Rusko": "Moskva",
    "San Marino": "San Marino",
    "Srbsko": "Bělehrad",
    "Slovensko": "Bratislava",
    "Slovinsko": "Lublaň",
    "Španělsko": "Madrid",
    "Švédsko": "Stockholm",
    "Švýcarsko": "Curych",
    "Turecko": "Ankara",
    "Ukrajina": "Kyjev",
    "Spojené království": "Londýn",
    "Vatikán": "Vatikán"
};

export default europeanCountriesAndCapitals;
