const usStatesAndCapitals = {
    "Alabama": "Montgomery",
    "Aljaška": "Juneau",
    "Arizona": "Phoenix",
    "Arkansas": "Little Rock",
    "Kalifornie": "Sacramento",
    "Colorado": "Denver",
    "Connecticut": "Hartford",
    "Delaware": "Dover",
    "Florida": "Tallahassee",
    "Georgie": "Atlanta",
    "Havaj": "Honolulu",
    "Idaho": "Boise",
    "Illinois": "Springfield",
    "Indiana": "Indianapolis",
    "Iowa": "Des Moines",
    "Kansas": "Topeka",
    "Kentucky": "Frankfort",
    "Louisiana": "Baton Rouge",
    "Maine": "Augusta",
    "Maryland": "Annapolis",
    "Massachusetts": "Boston",
    "Michigan": "Lansing",
    "Minnesota": "St. Paul",
    "Mississippi": "Jackson",
    "Missouri": "Jefferson City",
    "Montana": "Helena",
    "Nebraska": "Lincoln",
    "Nevada": "Carson City",
    "New Hampshire": "Concord",
    "New Jersey": "Trenton",
    "Nové Mexiko": "Santa Fe",
    "New York": "Albany",
    "Severní Karolína": "Raleigh",
    "Severní Dakota": "Bismarck",
    "Ohio": "Columbus",
    "Oklahoma": "Oklahoma City",
    "Oregon": "Salem",
    "Pensylvánie": "Harrisburg",
    "Rhode Island": "Providence",
    "Jižní Karolína": "Columbia",
    "Jižní Dakota": "Pierre",
    "Tennessee": "Nashville",
    "Texas": "Austin",
    "Utah": "Salt Lake City",
    "Vermont": "Montpelier",
    "Virginie": "Richmond",
    "Washington": "Olympia",
    "Západní Virginie": "Charleston",
    "Wisconsin": "Madison",
    "Wyoming": "Cheyenne"
};

export default usStatesAndCapitals;
