const easiestCountriesAndCapitals = {
    "Australia": "Canberra",
    "Austria": "Vienna",
    "Belgium": "Brussels",
    "Brazil": "Brasília",
    "Canada": "Ottawa",
    "China": "Beijing",
    "Denmark": "Copenhagen",
    "Egypt": "Cairo",
    "Finland": "Helsinki",
    "France": "Paris",
    "Germany": "Berlin",
    "Greece": "Athens",
    "India": "New Delhi",
    "Indonesia": "Jakarta",
    "Iran": "Tehran",
    "Iraq": "Baghdad",
    "Ireland": "Dublin",
    "Italy": "Rome",
    "Japan": "Tokyo",
    "Mexico": "Mexico City",
    "Netherlands": "Amsterdam",
    "New Zealand": "Wellington",
    "Norway": "Oslo",
    "Pakistan": "Islamabad",
    "Peru": "Lima",
    "Philippines": "Manila",
    "Poland": "Warsaw",
    "Portugal": "Lisbon",
    "Russia": "Moscow",
    "Saudi Arabia": "Riyadh",
    "South Africa": "Cape Town",
    "South Korea": "Seoul",
    "Spain": "Madrid",
    "Sweden": "Stockholm",
    "Switzerland": "Bern",
    "Thailand": "Bangkok",
    "Turkey": "Ankara",
    "Ukraine": "Kyiv",
    "United Arab Emirates": "Abu Dhabi",
    "United Kingdom": "London",
    "United States": "Washington, D.C.",
    "Vietnam": "Hanoi"
};

export default easiestCountriesAndCapitals;
