const usStatesAndCapitals = {
    "Alabama": "Montgomery",
    "Alaska": "Juneau",
    "Arizona": "Phoenix",
    "Arkansas": "Little Rock",
    "California": "Sacramento",
    "Colorado": "Denver",
    "Connecticut": "Hartford",
    "Delaware": "Dover",
    "Florida": "Tallahassee",
    "Georgia": "Atlanta",
    "Hawái": "Honolulu",
    "Idaho": "Boise",
    "Illinois": "Springfield",
    "Indiana": "Indianápolis",
    "Iowa": "Des Moines",
    "Kansas": "Topeka",
    "Kentucky": "Frankfort",
    "Luisiana": "Baton Rouge",
    "Maine": "Augusta",
    "Maryland": "Annapolis",
    "Massachusetts": "Boston",
    "Míchigan": "Lansing",
    "Minnesota": "Saint Paul",
    "Misisipi": "Jackson",
    "Misuri": "Jefferson City",
    "Montana": "Helena",
    "Nebraska": "Lincoln",
    "Nevada": "Carson City",
    "Nuevo Hampshire": "Concord",
    "Nueva Jersey": "Trenton",
    "Nuevo México": "Santa Fe",
    "Nueva York": "Albany",
    "Carolina del Norte": "Raleigh",
    "Dakota del Norte": "Bismarck",
    "Ohio": "Columbus",
    "Oklahoma": "Oklahoma City",
    "Oregón": "Salem",
    "Pensilvania": "Harrisburg",
    "Rhode Island": "Providence",
    "Carolina del Sur": "Columbia",
    "Dakota del Sur": "Pierre",
    "Tennessee": "Nashville",
    "Texas": "Austin",
    "Utah": "Salt Lake City",
    "Vermont": "Montpelier",
    "Virginia": "Richmond",
    "Washington": "Olympia",
    "Virginia Occidental": "Charleston",
    "Wisconsin": "Madison",
    "Wyoming": "Cheyenne"
};

export default usStatesAndCapitals;
