const easiestCountriesAndCapitals = {
    "Australia": "Canberra",
    "Austria": "Viena",
    "Bélgica": "Bruselas",
    "Brasil": "Brasilia",
    "Canadá": "Ottawa",
    "China": "Pekín",
    "Dinamarca": "Copenhague",
    "Egipto": "El Cairo",
    "Finlandia": "Helsinki",
    "Francia": "París",
    "Alemania": "Berlín",
    "Grecia": "Atenas",
    "India": "Nueva Delhi",
    "Indonesia": "Yakarta",
    "Irán": "Teherán",
    "Irak": "Bagdad",
    "Irlanda": "Dublín",
    "Italia": "Roma",
    "Japón": "Tokio",
    "México": "Ciudad de México",
    "Países Bajos": "Ámsterdam",
    "Nueva Zelanda": "Wellington",
    "Noruega": "Oslo",
    "Pakistán": "Islamabad",
    "Perú": "Lima",
    "Filipinas": "Manila",
    "Polonia": "Varsovia",
    "Portugal": "Lisboa",
    "Rusia": "Moscú",
    "Arabia Saudita": "Riad",
    "Sudáfrica": "Ciudad del Cabo",
    "Corea del Sur": "Seúl",
    "España": "Madrid",
    "Suecia": "Estocolmo",
    "Suiza": "Zúrich",
    "Tailandia": "Bangkok",
    "Turquía": "Ankara",
    "Ucrania": "Kiev",
    "Emiratos Árabes Unidos": "Abu Dabi",
    "Reino Unido": "Londres",
    "Estados Unidos": "Washington, D.C.",
    "Vietnam": "Hanói"
};

export default easiestCountriesAndCapitals;
