const europeanCountriesAndCapitals = {
    "Albania": "Tirana",
    "Andorra": "Andorra la Vieja",
    "Austria": "Viena",
    "Bielorrusia": "Minsk",
    "Bélgica": "Bruselas",
    "Bosnia y Herzegovina": "Sarajevo",
    "Bulgaria": "Sofía",
    "Croacia": "Zagreb",
    "Chipre": "Nicosia",
    "República Checa": "Praga",
    "Dinamarca": "Copenhague",
    "Estonia": "Tallin",
    "Finlandia": "Helsinki",
    "Francia": "París",
    "Alemania": "Berlín",
    "Grecia": "Atenas",
    "Hungría": "Budapest",
    "Islandia": "Reikiavik",
    "Irlanda": "Dublín",
    "Italia": "Roma",
    "Kosovo": "Pristina",
    "Letonia": "Riga",
    "Liechtenstein": "Vaduz",
    "Lituania": "Vilna",
    "Luxemburgo": "Luxemburgo",
    "Malta": "La Valeta",
    "Moldavia": "Chisinau",
    "Mónaco": "Mónaco",
    "Montenegro": "Podgorica",
    "Países Bajos": "Ámsterdam",
    "Macedonia del Norte": "Skopie",
    "Noruega": "Oslo",
    "Polonia": "Varsovia",
    "Portugal": "Lisboa",
    "Rumania": "Bucarest",
    "Rusia": "Moscú",
    "San Marino": "San Marino",
    "Serbia": "Belgrado",
    "Eslovaquia": "Bratislava",
    "Eslovenia": "Liubliana",
    "España": "Madrid",
    "Suecia": "Estocolmo",
    "Suiza": "Zúrich",
    "Turquía": "Ankara",
    "Ucrania": "Kiev",
    "Reino Unido": "Londres",
    "Ciudad del Vaticano": "Ciudad del Vaticano"
};

export default europeanCountriesAndCapitals;
