const asianCountriesAndCapitals = {
    "Afganistán": "Kabul",
    "Armenia": "Ereván",
    "Azerbaiyán": "Bakú",
    "Baréin": "Manama",
    "Bangladés": "Daca",
    "Bután": "Thimphu",
    "Brunéi": "Bandar Seri Begawan",
    "Camboya": "Nom Pen",
    "China": "Pekín",
    "Chipre": "Nicosia",
    "Georgia": "Tiflis",
    "India": "Nueva Delhi",
    "Indonesia": "Yakarta",
    "Irán": "Teherán",
    "Irak": "Bagdad",
    "Israel": "Jerusalén",
    "Japón": "Tokio",
    "Jordania": "Amán",
    "Kazajistán": "Nursultán",
    "Kuwait": "Kuwait",
    "Kirguistán": "Biskek",
    "Laos": "Vientián",
    "Líbano": "Beirut",
    "Malasia": "Kuala Lumpur",
    "Maldivas": "Malé",
    "Mongolia": "Ulán Bator",
    "Birmania": "Naypidó",
    "Nepal": "Katmandú",
    "Corea del Norte": "Pionyang",
    "Omán": "Mascate",
    "Pakistán": "Islamabad",
    "Filipinas": "Manila",
    "Catar": "Doha",
    "Arabia Saudita": "Riad",
    "Singapur": "Singapur",
    "Corea del Sur": "Seúl",
    "Sri Lanka": "Colombo",
    "Siria": "Damasco",
    "Taiwán": "Taipéi",
    "Tayikistán": "Dusambé",
    "Tailandia": "Bangkok",
    "Timor Oriental": "Dili",
    "Turquía": "Ankara",
    "Turkmenistán": "Asjabad",
    "Emiratos Árabes Unidos": "Abu Dabi",
    "Uzbekistán": "Taskent",
    "Vietnam": "Hanói",
    "Yemen": "Saná"
};

export default asianCountriesAndCapitals;
