const americanCountriesAndCapitals = {
    "Argentina": "Buenos Aires",
    "Bolivia": "Sucre",
    "Brasil": "Brasilia",
    "Chile": "Santiago",
    "Colombia": "Bogotá",
    "Ecuador": "Quito",
    "Guyana": "Georgetown",
    "Paraguay": "Asunción",
    "Perú": "Lima",
    "Surinam": "Paramaribo",
    "Uruguay": "Montevideo",
    "Venezuela": "Caracas",
    "Antigua y Barbuda": "Saint John's",
    "Bahamas": "Nasáu",
    "Barbados": "Bridgetown",
    "Belice": "Belmopán",
    "Canadá": "Ottawa",
    "Costa Rica": "San José",
    "Cuba": "La Habana",
    "Dominica": "Roseau",
    "República Dominicana": "Santo Domingo",
    "El Salvador": "San Salvador",
    "Granada": "Saint George's",
    "Guatemala": "Ciudad de Guatemala",
    "Haití": "Puerto Príncipe",
    "Honduras": "Tegucigalpa",
    "Jamaica": "Kingston",
    "México": "Ciudad de México",
    "Nicaragua": "Managua",
    "Panamá": "Ciudad de Panamá",
    "San Cristóbal y Nieves": "Basseterre",
    "Santa Lucía": "Castries",
    "San Vicente y las Granadinas": "Kingstown",
    "Trinidad y Tobago": "Puerto España",
    "Estados Unidos": "Washington D.C."
};

export default americanCountriesAndCapitals;
