const africanCountriesAndCapitals = {
    "Argelia": "Argel",
    "Angola": "Luanda",
    "Benín": "Porto-Novo",
    "Botsuana": "Gaborone",
    "Burkina Faso": "Uagadugú",
    "Burundi": "Gitega",
    "Cabo Verde": "Praia",
    "Camerún": "Yaundé",
    "República Centroafricana": "Bangui",
    "Chad": "Yamena",
    "Comoras": "Moroni",
    "República Democrática del Congo": "Kinshasa",
    "República del Congo": "Brazzaville",
    "Yibuti": "Yibuti",
    "Egipto": "El Cairo",
    "Guinea Ecuatorial": "Malabo",
    "Eritrea": "Asmara",
    "Esuatini": "Mbabane",
    "Etiopía": "Adís Abeba",
    "Gabón": "Libreville",
    "Gambia": "Banjul",
    "Ghana": "Acra",
    "Guinea": "Conakry",
    "Guinea-Bisáu": "Bisáu",
    "Costa de Marfil": "Yamusukro",
    "Kenia": "Nairobi",
    "Lesoto": "Maseru",
    "Liberia": "Monrovia",
    "Libia": "Trípoli",
    "Madagascar": "Antananarivo",
    "Malaui": "Lilongüe",
    "Malí": "Bamako",
    "Mauritania": "Nuakchot",
    "Mauricio": "Port Louis",
    "Marruecos": "Rabat",
    "Mozambique": "Maputo",
    "Namibia": "Windhoek",
    "Níger": "Niamey",
    "Nigeria": "Abuya",
    "Ruanda": "Kigali",
    "Santo Tomé y Príncipe": "Santo Tomé",
    "Senegal": "Dakar",
    "Seychelles": "Victoria",
    "Sierra Leona": "Freetown",
    "Somalia": "Mogadiscio",
    "Sudáfrica": "Pretoria",
    "Sudán del Sur": "Yuba",
    "Sudán": "Jartum",
    "Tanzania": "Dodoma",
    "Togo": "Lomé",
    "Túnez": "Túnez",
    "Uganda": "Kampala",
    "Zambia": "Lusaka",
    "Zimbabue": "Harare"
};

export default africanCountriesAndCapitals;
